/-
Copyright (c) 2024 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import Mathlib.LinearAlgebra.Matrix.Transvection
import Mathlib.LinearAlgebra.Matrix.SpecialLinearGroup

/-!
# SL_n(ℤ) is generated by transvections

Every element of `SL_n(ℤ)` can be written as a product of elementary
transvection matrices `E_{ij}(c) = I + c·e_{ij}`.

## Main results

* `SLnZ_transvec_gen` — every `σ ∈ SL_n(ℤ)` equals `L.prod` for a list `L`
  of transvections.
-/

/-- An elementary transvection in `SL_m(ℤ)`: the matrix `I + c·e_{ij}`. -/
def slTransvecG {m : ℕ} (i j : Fin m) (hij : i ≠ j) (c : ℤ) :
    Matrix.SpecialLinearGroup (Fin m) ℤ :=
  ⟨Matrix.transvection i j c, Matrix.det_transvection_of_ne i j hij c⟩

/-- A matrix in `SL_m(ℤ)` is a transvection if it equals `slTransvecG i j hij c`
for some `i ≠ j` and scalar `c`. -/
def IsTransvec {m : ℕ} (E : Matrix.SpecialLinearGroup (Fin m) ℤ) : Prop :=
  ∃ (i j : Fin m) (hij : i ≠ j) (c : ℤ), E = slTransvecG i j hij c

private lemma slTransvecG_mul {m : ℕ} (i j : Fin m) (hij : i ≠ j) (a b : ℤ) :
    slTransvecG i j hij a * slTransvecG i j hij b = slTransvecG i j hij (a + b) :=
  Subtype.ext (Matrix.transvection_mul_transvection_same i j hij a b)

private lemma slTransvecG_zero {m : ℕ} (i j : Fin m) (hij : i ≠ j) :
    slTransvecG i j hij 0 = 1 :=
  Subtype.ext (Matrix.transvection_zero i j)

private lemma slTransvecG_mul_entry {m : ℕ} [NeZero m] (i j : Fin m) (hij : i ≠ j) (c : ℤ)
    (σ : Matrix.SpecialLinearGroup (Fin m) ℤ) (a b : Fin m) :
    (slTransvecG i j hij c * σ).1 a b =
    if a = i then σ.1 i b + c * σ.1 j b else σ.1 a b := by
  change (Matrix.transvection i j c * σ.1) a b = _
  split_ifs with ha
  · subst a
    exact Matrix.transvection_mul_apply_same (i := i) (j := j) (b := b) (c := c) (M := σ.1)
  · exact Matrix.transvection_mul_apply_of_ne (i := i) (j := j) (a := a) (b := b)
      (ha := ha) (c := c) (M := σ.1)

private lemma slTransvecG_mul_right_entry {m : ℕ} [NeZero m] (i j : Fin m) (hij : i ≠ j) (c : ℤ)
    (σ : Matrix.SpecialLinearGroup (Fin m) ℤ) (a b : Fin m) :
    (σ * slTransvecG i j hij c).1 a b =
    if b = j then σ.1 a j + c * σ.1 a i else σ.1 a b := by
  change (σ.1 * Matrix.transvection i j c) a b = _
  split_ifs with hb
  · subst b
    exact Matrix.mul_transvection_apply_same (i := i) (j := j) (a := a) (c := c) (M := σ.1)
  · exact Matrix.mul_transvection_apply_of_ne (i := i) (j := j) (a := a) (b := b)
      (hb := hb) (c := c) (M := σ.1)

private lemma isTransvec_append {m : ℕ} (L₁ L₂ : List (Matrix.SpecialLinearGroup (Fin m) ℤ))
    (h₁ : ∀ E ∈ L₁, IsTransvec E) (h₂ : ∀ E ∈ L₂, IsTransvec E) :
    ∀ E ∈ L₁ ++ L₂, IsTransvec E :=
  fun E hE ↦ (List.mem_append.mp hE).elim (h₁ E) (h₂ E)

private def col0Sum {m : ℕ} (σ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ) : ℕ :=
  ∑ i : Fin (m+1), (σ.1 i 0).natAbs

private lemma col0_ne_zero {m : ℕ} (σ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ) :
    ∃ i, σ.1 i 0 ≠ 0 := by
  by_contra! h
  exact absurd (Matrix.det_eq_zero_of_column_eq_zero 0 (fun i ↦ h i)) (by rw [σ.2]; norm_num)

private def nzCount {m : ℕ} (σ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ) : ℕ :=
  (Finset.univ.filter fun i : Fin (m+1) ↦ σ.1 i 0 ≠ 0).card

private lemma exists_two_nz {m : ℕ} (σ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)
    (h : 2 ≤ nzCount σ) :
    ∃ (i j : Fin (m+1)), i ≠ j ∧ σ.1 i 0 ≠ 0 ∧ σ.1 j 0 ≠ 0 := by
  simp only [nzCount] at h
  have h1 : 1 < (Finset.univ.filter fun i : Fin (m+1) ↦ σ.1 i 0 ≠ 0).card := by lia
  obtain ⟨i, hi, j, hj, hij⟩ := Finset.one_lt_card.mp h1
  simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hi hj
  exact ⟨i, j, hij, hi, hj⟩

private lemma col0_euclidean_step_aux {m : ℕ} (σ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)
    (i j : Fin (m+1)) (hij : i ≠ j) (hj : σ.1 j 0 ≠ 0)
    (hle : (σ.1 j 0).natAbs ≤ (σ.1 i 0).natAbs) :
    col0Sum (slTransvecG i j hij (-(σ.1 i 0 / σ.1 j 0)) * σ) < col0Sum σ := by
  set q := σ.1 i 0 / σ.1 j 0
  have h_new : (slTransvecG i j hij (-q) * σ).1 i 0 = σ.1 i 0 % σ.1 j 0 := by
    rw [slTransvecG_mul_entry]; simp only [ite_true]
    linarith [(Int.mul_ediv_add_emod (σ.1 i 0) (σ.1 j 0)).symm]
  have h_oth : ∀ a, a ≠ i → (slTransvecG i j hij (-q) * σ).1 a 0 = σ.1 a 0 :=
    fun a ha ↦ by rw [slTransvecG_mul_entry]; simp [ha]
  have h_rem : (σ.1 i 0 % σ.1 j 0).natAbs < (σ.1 j 0).natAbs := by
    have h1 := Int.emod_nonneg (σ.1 i 0) hj
    have h2 : σ.1 i 0 % σ.1 j 0 < |σ.1 j 0| := by
      rw [← Int.emod_abs]; exact Int.emod_lt_of_pos _ (abs_pos.mpr hj)
    exact_mod_cast show ((σ.1 i 0 % σ.1 j 0).natAbs : ℤ) < (σ.1 j 0).natAbs from by
      rw [Int.natAbs_of_nonneg h1, Int.natCast_natAbs]; exact h2
  simp only [col0Sum]
  rw [← Finset.add_sum_erase _ _ (Finset.mem_univ i),
      ← Finset.add_sum_erase _ _ (Finset.mem_univ i)]
  have h_rest : ∑ k ∈ Finset.univ.erase i,
      ((slTransvecG i j hij (-q) * σ).1 k 0).natAbs =
      ∑ k ∈ Finset.univ.erase i, (σ.1 k 0).natAbs :=
    Finset.sum_congr rfl fun k hk ↦ by rw [h_oth k (Finset.mem_erase.mp hk).1]
  rw [h_rest, h_new]; linarith [Nat.lt_of_lt_of_le h_rem hle]

private lemma col0_euclidean_step {m : ℕ} (σ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)
    (h : 2 ≤ nzCount σ) :
    ∃ (i j : Fin (m+1)) (hij : i ≠ j) (c : ℤ),
      col0Sum (slTransvecG i j hij c * σ) < col0Sum σ := by
  obtain ⟨i₀, j₀, hij₀, hi₀, hj₀⟩ := exists_two_nz σ h
  by_cases hge : (σ.1 j₀ 0).natAbs ≤ (σ.1 i₀ 0).natAbs
  · exact ⟨i₀, j₀, hij₀, _, col0_euclidean_step_aux σ i₀ j₀ hij₀ hj₀ hge⟩
  · push Not at hge
    exact ⟨j₀, i₀, hij₀.symm, _, col0_euclidean_step_aux σ j₀ i₀ hij₀.symm hi₀ hge.le⟩

private lemma col0_reduce {m : ℕ} (σ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ) :
    ∃ (L : List (Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)),
      (∀ E ∈ L, IsTransvec E) ∧ nzCount (L.prod * σ) ≤ 1 := by
  suffices key : ∀ (k : ℕ) (τ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ),
      col0Sum τ ≤ k → ∃ (L : List (Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)),
        (∀ E ∈ L, IsTransvec E) ∧ nzCount (L.prod * τ) ≤ 1 from
    key (col0Sum σ) σ le_rfl
  intro k
  induction k using Nat.strongRecOn with
  | _ k ihk =>
  intro τ hk
  by_cases hn : nzCount τ ≤ 1
  · exact ⟨[], fun _ h ↦ absurd h (by simp), by simp; exact hn⟩
  · push Not at hn
    obtain ⟨i, j, hij, c, hlt⟩ := col0_euclidean_step τ hn
    set τ' := slTransvecG i j hij c * τ
    have hlt' : col0Sum τ' < k := Nat.lt_of_lt_of_le hlt hk
    obtain ⟨L, hL, hL_nz⟩ := ihk (col0Sum τ') hlt' τ' le_rfl
    exact ⟨L ++ [slTransvecG i j hij c], fun E hE ↦ by
      simp only [List.mem_append, List.mem_cons, List.mem_nil_iff, or_false] at hE
      exact hE.elim (hL E) (fun h ↦ h ▸ ⟨i, j, hij, c, rfl⟩),
      by rw [List.prod_append, List.prod_cons, List.prod_nil, mul_one, mul_assoc]; exact hL_nz⟩

private lemma slTransvecG_inv {m : ℕ} (i j : Fin m) (hij : i ≠ j) (c : ℤ) :
    (slTransvecG i j hij c)⁻¹ = slTransvecG i j hij (-c) :=
  mul_left_cancel (a := slTransvecG i j hij c) <| by
    rw [mul_inv_cancel, slTransvecG_mul, add_neg_cancel, slTransvecG_zero]

private lemma isTransvec_inv {m : ℕ} {E : Matrix.SpecialLinearGroup (Fin m) ℤ}
    (hE : IsTransvec E) : IsTransvec E⁻¹ := by
  obtain ⟨i, j, hij, c, rfl⟩ := hE
  rw [slTransvecG_inv]; exact ⟨i, j, hij, -c, rfl⟩

private lemma transvec_list_inv {m : ℕ} (L : List (Matrix.SpecialLinearGroup (Fin m) ℤ))
    (hL : ∀ E ∈ L, IsTransvec E) :
    ∃ L' : List (Matrix.SpecialLinearGroup (Fin m) ℤ),
      (∀ E ∈ L', IsTransvec E) ∧ L.prod⁻¹ = L'.prod := by
  refine ⟨(L.map (·⁻¹)).reverse, fun E hE ↦ ?_, List.prod_inv_reverse L⟩
  rw [List.mem_reverse, List.mem_map] at hE
  obtain ⟨F, hF, rfl⟩ := hE; exact isTransvec_inv (hL F hF)

private def blockLift {m : ℕ} (i j : Fin m) (hij : i ≠ j) (c : ℤ) :
    Matrix.SpecialLinearGroup (Fin (m + 1)) ℤ :=
  slTransvecG i.succ j.succ (fun h ↦ hij (Fin.succ_injective m h)) c

private lemma blockLift_isTransvec {m : ℕ} (i j : Fin m) (hij : i ≠ j) (c : ℤ) :
    IsTransvec (blockLift i j hij c) :=
  ⟨i.succ, j.succ, fun h ↦ hij (Fin.succ_injective m h), c, rfl⟩

private lemma blockLift_entry {m : ℕ} (i j : Fin m) (hij : i ≠ j) (c : ℤ)
    (τ : Matrix.SpecialLinearGroup (Fin (m + 1)) ℤ) (a b : Fin (m + 1)) :
    (blockLift i j hij c * τ).1 a b =
    if a = i.succ then τ.1 i.succ b + c * τ.1 j.succ b else τ.1 a b := by
  unfold blockLift; exact slTransvecG_mul_entry i.succ j.succ _ c τ a b

private lemma blockLift_row0 {m : ℕ} (i j : Fin m) (hij : i ≠ j) (c : ℤ)
    (τ : Matrix.SpecialLinearGroup (Fin (m + 1)) ℤ) (b : Fin (m + 1)) :
    (blockLift i j hij c * τ).1 0 b = τ.1 0 b := by
  rw [blockLift_entry]; split_ifs with h
  · exact absurd h.symm (Fin.succ_ne_zero i)
  · rfl

private lemma blockLift_col0 {m : ℕ} (i j : Fin m) (hij : i ≠ j) (c : ℤ)
    (τ : Matrix.SpecialLinearGroup (Fin (m + 1)) ℤ)
    (hcol : ∀ k : Fin (m + 1), k ≠ 0 → τ.1 k 0 = 0) (a : Fin (m + 1)) :
    (blockLift i j hij c * τ).1 a 0 = τ.1 a 0 := by
  rw [blockLift_entry]; split_ifs with ha
  · subst ha; rw [hcol j.succ (Fin.succ_ne_zero j), mul_zero, add_zero]
  · rfl

private lemma det_lowerRight {m : ℕ} (τ : Matrix.SpecialLinearGroup (Fin (m + 1)) ℤ)
    (h00 : τ.1 0 0 = 1) (h0j : ∀ j : Fin (m + 1), j ≠ 0 → τ.1 0 j = 0) :
    (Matrix.of fun (i : Fin m) (j : Fin m) ↦ τ.1 i.succ j.succ).det = 1 := by
  change (τ.1.submatrix Fin.succ Fin.succ).det = 1
  have hdet : τ.1.det = 1 := τ.2
  rw [Matrix.det_succ_row_zero, Finset.sum_eq_single (0 : Fin (m + 1))
    (fun j _ hj ↦ by simp [h0j j hj])
    (fun h ↦ absurd (Finset.mem_univ _) h)] at hdet
  simpa [Fin.succAbove_zero, h00] using hdet

private def extractBlock {m : ℕ} (τ : Matrix.SpecialLinearGroup (Fin (m + 1)) ℤ)
    (h00 : τ.1 0 0 = 1) (h0j : ∀ j : Fin (m + 1), j ≠ 0 → τ.1 0 j = 0)
    (_hi0 : ∀ i : Fin (m + 1), i ≠ 0 → τ.1 i 0 = 0) :
    Matrix.SpecialLinearGroup (Fin m) ℤ :=
  ⟨Matrix.of fun i j ↦ τ.1 i.succ j.succ, det_lowerRight τ h00 h0j⟩

private lemma extractBlock_blockLift {m : ℕ} (i j : Fin m) (hij : i ≠ j) (c : ℤ)
    (τ : Matrix.SpecialLinearGroup (Fin (m + 1)) ℤ)
    (h00 : τ.1 0 0 = 1) (h0j : ∀ j, j ≠ 0 → τ.1 0 j = 0)
    (hi0 : ∀ i, i ≠ 0 → τ.1 i 0 = 0) :
    extractBlock (blockLift i j hij c * τ)
      (by rw [blockLift_row0]; exact h00)
      (by intro k hk; rw [blockLift_row0]; exact h0j k hk)
      (by intro k hk; rw [blockLift_col0 _ _ _ _ _ hi0]; exact hi0 k hk) =
    slTransvecG i j hij c * extractBlock τ h00 h0j hi0 := by
  haveI : NeZero m := ⟨by rintro rfl; exact i.elim0⟩
  apply Subtype.ext; ext a b
  change (blockLift i j hij c * τ).1 a.succ b.succ =
    (slTransvecG i j hij c * extractBlock τ h00 h0j hi0).1 a b
  rw [blockLift_entry i j hij c τ a.succ b.succ,
      slTransvecG_mul_entry i j hij c (extractBlock τ h00 h0j hi0) a b]
  simp only [Fin.succ_inj, extractBlock, Matrix.of_apply]

private def row0Sum {m : ℕ} (σ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ) : ℕ :=
  ∑ j : Fin (m+1), if (j : ℕ) = 0 then 0 else (σ.1 0 j).natAbs

private lemma row0Sum_eq_zero_imp_cleared {m : ℕ} (σ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)
    (hzero : row0Sum σ = 0) (j : Fin (m+1)) (hj : j ≠ 0) : σ.1 0 j = 0 := by
  have h_le : (if (j : ℕ) = 0 then 0 else (σ.1 0 j).natAbs) ≤ row0Sum σ :=
    Finset.single_le_sum
      (f := fun (j : Fin (m + 1)) ↦ if (j : ℕ) = 0 then 0 else (σ.1 0 j).natAbs)
      (fun _ _ ↦ Nat.zero_le _) (Finset.mem_univ j)
  simp only [hzero, Fin.val_eq_zero_iff.not.mpr hj, ↓reduceIte] at h_le
  exact Int.natAbs_eq_zero.mp (Nat.eq_zero_of_le_zero h_le)

private lemma row0_clear_step {m : ℕ} (σ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)
    (hσ00 : σ.1 0 0 = 1) (hσi0 : ∀ i, i ≠ 0 → σ.1 i 0 = 0) (hzero : row0Sum σ ≠ 0) :
    ∃ E, IsTransvec E ∧ (σ * E).1 0 0 = 1 ∧ (∀ i, i ≠ 0 → (σ * E).1 i 0 = 0) ∧
      row0Sum (σ * E) < row0Sum σ := by
  haveI : NeZero (m + 1) := ⟨Nat.succ_ne_zero m⟩
  have ⟨j₀, hj₀_nz⟩ : ∃ j : Fin (m + 1),
      (if (j : ℕ) = 0 then 0 else (σ.1 0 j).natAbs) ≠ 0 := by
    by_contra h; push Not at h
    exact hzero (Finset.sum_eq_zero (fun j _ ↦ h j))
  have hj₀ : j₀ ≠ 0 := fun h ↦ by subst h; simp at hj₀_nz
  have hj₀_val : (j₀ : ℕ) ≠ 0 := Fin.val_eq_zero_iff.not.mpr hj₀
  have hj₀_entry : σ.1 0 j₀ ≠ 0 := fun h ↦ by simp [h, hj₀_val] at hj₀_nz
  set E := slTransvecG (0 : Fin (m+1)) j₀ hj₀.symm (-σ.1 0 j₀)
  refine ⟨E, ⟨0, j₀, hj₀.symm, _, rfl⟩, ?_, ?_, ?_⟩
  · rw [slTransvecG_mul_right_entry]; simp [hj₀.symm, hσ00]
  · intro i hi; rw [slTransvecG_mul_right_entry]; simp [hj₀.symm, hσi0 i hi]
  · have hclear : (σ * E).1 0 j₀ = 0 := by
      rw [slTransvecG_mul_right_entry]; simp [hσ00]
    have hother : ∀ k, k ≠ j₀ → (σ * E).1 0 k = σ.1 0 k := fun k hk ↦ by
      rw [slTransvecG_mul_right_entry]; simp [hk]
    simp only [row0Sum]
    rw [← Finset.add_sum_erase _ _ (Finset.mem_univ j₀),
        ← Finset.add_sum_erase _ _ (Finset.mem_univ j₀)]
    have h_rest : ∑ k ∈ Finset.univ.erase j₀,
        (if (k : ℕ) = 0 then 0 else ((σ * E).1 0 k).natAbs) =
        ∑ k ∈ Finset.univ.erase j₀, (if (k : ℕ) = 0 then 0 else (σ.1 0 k).natAbs) :=
      Finset.sum_congr rfl fun k hk ↦ by
        by_cases h0 : (k : ℕ) = 0 <;> simp [h0, hother k (Finset.mem_erase.mp hk).1]
    rw [h_rest, hclear, show (if (j₀ : ℕ) = 0 then 0 else (0 : ℤ).natAbs) = 0 from by simp]
    simp only [hj₀_val, ↓reduceIte, zero_add]
    lia

private lemma row0_clear {m : ℕ} (τ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)
    (h00 : τ.1 0 0 = 1) (hi0 : ∀ i : Fin (m+1), i ≠ 0 → τ.1 i 0 = 0) :
    ∃ (L : List (Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)),
      (∀ E ∈ L, IsTransvec E) ∧
      (τ * L.prod).1 0 0 = 1 ∧
      (∀ j : Fin (m+1), j ≠ 0 → (τ * L.prod).1 0 j = 0) ∧
      (∀ i : Fin (m+1), i ≠ 0 → (τ * L.prod).1 i 0 = 0) := by
  suffices key : ∀ (k : ℕ) (σ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ),
      σ.1 0 0 = 1 → (∀ i, i ≠ 0 → σ.1 i 0 = 0) → row0Sum σ ≤ k →
      ∃ (L : List (Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)),
        (∀ E ∈ L, IsTransvec E) ∧
        (σ * L.prod).1 0 0 = 1 ∧
        (∀ j, j ≠ 0 → (σ * L.prod).1 0 j = 0) ∧
        (∀ i, i ≠ 0 → (σ * L.prod).1 i 0 = 0) from
    key (row0Sum τ) τ h00 hi0 le_rfl
  intro k; induction k using Nat.strongRecOn with
  | _ k ihk =>
  intro σ hσ00 hσi0 hk
  by_cases hzero : row0Sum σ = 0
  · exact ⟨[], fun _ h ↦ absurd h (by simp), by simp [hσ00],
      fun j hj ↦ by simpa using row0Sum_eq_zero_imp_cleared σ hzero j hj,
      fun i hi ↦ by simp [hσi0 i hi]⟩
  · obtain ⟨E, hE_tv, hσ'00, hσ'i0, hlt⟩ := row0_clear_step σ hσ00 hσi0 hzero
    obtain ⟨L', hL'_tv, hL'_00, hL'_0j, hL'_i0⟩ :=
      ihk (row0Sum (σ * E)) (by lia) (σ * E) hσ'00 hσ'i0 le_rfl
    refine ⟨E :: L',
      fun F hF ↦ (List.mem_cons.mp hF).elim (· ▸ hE_tv) (hL'_tv F), ?_, ?_, ?_⟩
    · simpa only [List.prod_cons, ← mul_assoc] using hL'_00
    · intro j hj; simpa only [List.prod_cons, ← mul_assoc] using hL'_0j j hj
    · intro i hi; simpa only [List.prod_cons, ← mul_assoc] using hL'_i0 i hi

private lemma nzCount_le_one_unique_nonzero {m : ℕ}
    (τ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)
    (i₀ : Fin (m+1)) (hi₀ : τ.1 i₀ 0 ≠ 0) (h_nz : nzCount τ ≤ 1) :
    ∀ k, k ≠ i₀ → τ.1 k 0 = 0 := by
  intro k hk; by_contra hne
  have h2 : 2 ≤ nzCount τ := calc
    2 = ({i₀, k} : Finset _).card := (Finset.card_pair hk.symm).symm
    _ ≤ nzCount τ := Finset.card_le_card fun x hx ↦ by
      simp only [Finset.mem_insert, Finset.mem_singleton] at hx
      simp only [Finset.mem_filter, Finset.mem_univ, true_and]
      exact hx.elim (· ▸ hi₀) (· ▸ hne)
  lia

private lemma sole_nonzero_col0_is_unit {m : ℕ} (τ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)
    (i₀ : Fin (m+1)) (h_others : ∀ k, k ≠ i₀ → τ.1 k 0 = 0) :
    τ.1 i₀ 0 = 1 ∨ τ.1 i₀ 0 = -1 := by
  set M := τ.1
  have hdet : M.det = 1 := τ.2
  rw [← Int.isUnit_iff]; apply isUnit_of_dvd_one; rw [← hdet, Matrix.det_apply]
  apply Finset.dvd_sum; intro σ _
  show M i₀ 0 ∣ (↑(Equiv.Perm.sign σ) : ℤ) * ∏ i, M (σ i) i
  rw [Fin.prod_univ_succ]
  by_cases hσ : σ 0 = i₀
  · rw [hσ, ← mul_assoc]; exact dvd_mul_of_dvd_left (dvd_mul_left _ _) _
  · rw [h_others (σ 0) hσ, zero_mul, mul_zero]; exact dvd_zero _

private lemma block_form_transvec_lift {m : ℕ} (M : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)
    (H00 : M.1 0 0 = 1) (H0j : ∀ j, j ≠ 0 → M.1 0 j = 0)
    (Hi0 : ∀ i, i ≠ 0 → M.1 i 0 = 0)
    (L : List (Matrix.SpecialLinearGroup (Fin m) ℤ)) (hL : ∀ E ∈ L, IsTransvec E)
    (hL_eq : extractBlock M H00 H0j Hi0 = L.prod) :
    ∃ (L' : List (Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)),
      (∀ E ∈ L', IsTransvec E) ∧ M = L'.prod := by
  induction L generalizing M with
  | nil =>
    refine ⟨[], fun _ h ↦ absurd h (by simp), ?_⟩
    simp only [List.prod_nil] at hL_eq ⊢
    apply Subtype.ext; ext a b
    simp only [Matrix.SpecialLinearGroup.coe_one, Matrix.one_apply]
    by_cases ha : a = 0
    · subst ha; by_cases hb : b = 0
      · subst hb; exact H00
      · rw [H0j b hb, if_neg (Ne.symm hb)]
    · by_cases hb : b = 0
      · subst hb; rw [Hi0 a ha, if_neg ha]
      · obtain ⟨a', rfl⟩ := Fin.exists_succ_eq.mpr ha
        obtain ⟨b', rfl⟩ := Fin.exists_succ_eq.mpr hb
        have h := congr_fun (congr_fun (congr_arg Subtype.val hL_eq) a') b'
        simp only [extractBlock, Matrix.of_apply, Matrix.SpecialLinearGroup.coe_one,
          Matrix.one_apply] at h
        simpa using h
  | cons E L' ihL' =>
    simp only [List.prod_cons] at hL_eq
    obtain ⟨i, j, hij, c, rfl⟩ := hL E (List.mem_cons.mpr (Or.inl rfl))
    have H00' : (blockLift i j hij (-c) * M).1 0 0 = 1 := by
      rw [blockLift_row0]; exact H00
    have H0j' : ∀ k, k ≠ 0 → (blockLift i j hij (-c) * M).1 0 k = 0 := by
      intro k hk; rw [blockLift_row0]; exact H0j k hk
    have Hi0' : ∀ k, k ≠ 0 → (blockLift i j hij (-c) * M).1 k 0 = 0 := by
      intro k hk; rw [blockLift_col0 _ _ _ _ _ Hi0]; exact Hi0 k hk
    have hext' : extractBlock (blockLift i j hij (-c) * M) H00' H0j' Hi0' = L'.prod :=
      (extractBlock_blockLift i j hij (-c) M H00 H0j Hi0).trans
        (by rw [hL_eq, ← mul_assoc, slTransvecG_mul, neg_add_cancel, slTransvecG_zero, one_mul])
    obtain ⟨L'', hL''_tv, hL''_eq⟩ := ihL'
      (blockLift i j hij (-c) * M) H00' H0j' Hi0'
      (fun F hF ↦ hL F (List.mem_cons_of_mem _ hF)) hext'
    refine ⟨blockLift i j hij c :: L'',
      fun F hF ↦ (List.mem_cons.mp hF).elim
        (fun h ↦ h ▸ blockLift_isTransvec i j hij c) (hL''_tv F), ?_⟩
    simp only [List.prod_cons]; rw [← hL''_eq, ← mul_assoc]
    unfold blockLift; rw [slTransvecG_mul, add_neg_cancel, slTransvecG_zero, one_mul]

/-- Column-clearing for a `-1` pivot at the `(0,0)` position in dimension `≥ 2`:
three transvections turn the first column into the first standard basis vector. -/
private lemma column_pivot_of_neg_one_at_zero {m' : ℕ}
    (τ : Matrix.SpecialLinearGroup (Fin (m'+2)) ℤ) (h_neg1 : τ.1 0 0 = -1)
    (h_others : ∀ k, k ≠ 0 → τ.1 k 0 = 0) :
    ∃ (L₁ : List (Matrix.SpecialLinearGroup (Fin (m'+2)) ℤ)),
      (∀ E ∈ L₁, IsTransvec E) ∧ (L₁.prod * τ).1 0 0 = 1 ∧
      (∀ i, i ≠ 0 → (L₁.prod * τ).1 i 0 = 0) := by
  have h10 : (1 : Fin (m' + 2)) ≠ 0 := by simp
  have h01 : (0 : Fin (m' + 2)) ≠ 1 := h10.symm
  set σ₁ := slTransvecG (1 : Fin (m' + 2)) 0 h10 1 * τ
  have hσ₁_00 : σ₁.1 0 0 = -1 := by rw [slTransvecG_mul_entry]; simp [h01, h_neg1]
  have hσ₁_10 : σ₁.1 1 0 = -1 := by
    rw [slTransvecG_mul_entry]; simp [h_neg1, h_others 1 h10]
  have hσ₁_i0 : ∀ i, i ≠ 0 → i ≠ 1 → σ₁.1 i 0 = 0 := fun i hi0 hi1 ↦ by
    rw [slTransvecG_mul_entry]; simp [hi1, h_others i hi0]
  set σ₂ := slTransvecG (0 : Fin (m' + 2)) 1 h01 (-2) * σ₁
  have hσ₂_00 : σ₂.1 0 0 = 1 := by rw [slTransvecG_mul_entry]; simp [hσ₁_00, hσ₁_10]
  have hσ₂_10 : σ₂.1 1 0 = -1 := by rw [slTransvecG_mul_entry]; simp [h10, hσ₁_10]
  have hσ₂_i0 : ∀ i, i ≠ 0 → i ≠ 1 → σ₂.1 i 0 = 0 := fun i hi0 hi1 ↦ by
    rw [slTransvecG_mul_entry]; simp [hi0, hσ₁_i0 i hi0 hi1]
  set σ₃ := slTransvecG (1 : Fin (m' + 2)) 0 h10 1 * σ₂
  have hσ₃_00 : σ₃.1 0 0 = 1 := by rw [slTransvecG_mul_entry]; simp [h01, hσ₂_00]
  have hσ₃_i0 : ∀ i, i ≠ 0 → σ₃.1 i 0 = 0 := fun i hi ↦ by
    rw [slTransvecG_mul_entry]
    rcases eq_or_ne i 1 with rfl | hi1
    · simp [hσ₂_00, hσ₂_10]
    · simp [hi1, hσ₂_i0 i hi hi1]
  have hprod : [slTransvecG 1 0 h10 1, slTransvecG 0 1 h01 (-2),
      slTransvecG 1 0 h10 1].prod * τ = σ₃ := by
    simp only [List.prod_cons, List.prod_nil, mul_one, mul_assoc, σ₃, σ₂, σ₁]
  exact ⟨[slTransvecG 1 0 h10 1, slTransvecG 0 1 h01 (-2), slTransvecG 1 0 h10 1],
    fun E hE ↦ by
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hE
      rcases hE with rfl | rfl | rfl <;> exact ⟨_, _, _, _, rfl⟩,
    by rw [hprod]; exact hσ₃_00, fun i hi ↦ by rw [hprod]; exact hσ₃_i0 i hi⟩

/-- Column-clearing for a unit pivot `v ∈ {1, -1}` at an off-diagonal position `i₀ ≠ 0`:
two transvections turn the first column into the first standard basis vector. -/
private lemma column_pivot_of_unit_off_diagonal {m : ℕ} [NeZero (m + 1)]
    (τ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ) (i₀ : Fin (m+1)) (hi₀_zero : i₀ ≠ 0)
    (h_others : ∀ k, k ≠ i₀ → τ.1 k 0 = 0) (h_unit : τ.1 i₀ 0 = 1 ∨ τ.1 i₀ 0 = -1) :
    ∃ (L₁ : List (Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)),
      (∀ E ∈ L₁, IsTransvec E) ∧ (L₁.prod * τ).1 0 0 = 1 ∧
      (∀ i, i ≠ 0 → (L₁.prod * τ).1 i 0 = 0) := by
  have hi₀0 : (0 : Fin (m+1)) ≠ i₀ := fun h ↦ hi₀_zero h.symm
  set v := τ.1 i₀ 0 with hv_def
  have hv2 : v * v = 1 := by rcases h_unit with h | h <;> simp [v, h]
  set σ₁ := slTransvecG (0 : Fin (m+1)) i₀ hi₀0 v * τ
  have hσ₁_00 : σ₁.1 0 0 = 1 := by
    rw [slTransvecG_mul_entry]; simp [h_others 0 hi₀0, ← hv_def, hv2]
  have hσ₁_i₀0 : σ₁.1 i₀ 0 = v := by
    rw [slTransvecG_mul_entry]; simp [hi₀_zero, ← hv_def]
  have hσ₁_other : ∀ k, k ≠ 0 → k ≠ i₀ → σ₁.1 k 0 = 0 := fun k hk0 hki₀ ↦ by
    rw [slTransvecG_mul_entry]; simp [hk0, h_others k hki₀]
  set σ₂ := slTransvecG i₀ (0 : Fin (m+1)) hi₀_zero (-v) * σ₁
  have hσ₂_00 : σ₂.1 0 0 = 1 := by rw [slTransvecG_mul_entry]; simp [hi₀0, hσ₁_00]
  have hσ₂_i0 : ∀ i, i ≠ 0 → σ₂.1 i 0 = 0 := fun i hi ↦ by
    rw [slTransvecG_mul_entry]
    rcases eq_or_ne i i₀ with rfl | hne
    · simp [hσ₁_i₀0, hσ₁_00, add_neg_cancel]
    · simp [hne, hσ₁_other i hi hne]
  have hprod : [slTransvecG i₀ 0 hi₀_zero (-v),
      slTransvecG 0 i₀ hi₀0 v].prod * τ = σ₂ := by
    simp only [List.prod_cons, List.prod_nil, mul_one, mul_assoc, σ₂, σ₁]
  exact ⟨[slTransvecG i₀ 0 hi₀_zero (-v), slTransvecG 0 i₀ hi₀0 v],
    fun E hE ↦ by
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hE
      rcases hE with rfl | rfl <;> exact ⟨_, _, _, _, rfl⟩,
    by rw [hprod]; exact hσ₂_00, fun i hi ↦ by rw [hprod]; exact hσ₂_i0 i hi⟩

private lemma to_block_form {m : ℕ} (τ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)
    (i₀ : Fin (m+1)) (hi₀ : τ.1 i₀ 0 ≠ 0) (h_others : ∀ k, k ≠ i₀ → τ.1 k 0 = 0)
    (h_unit : τ.1 i₀ 0 = 1 ∨ τ.1 i₀ 0 = -1) :
    ∃ (L_left L_right : List (Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)),
      (∀ E ∈ L_left, IsTransvec E) ∧ (∀ E ∈ L_right, IsTransvec E) ∧
      (L_left.prod * τ * L_right.prod).1 0 0 = 1 ∧
      (∀ j : Fin (m+1), j ≠ 0 → (L_left.prod * τ * L_right.prod).1 0 j = 0) ∧
      (∀ i : Fin (m+1), i ≠ 0 → (L_left.prod * τ * L_right.prod).1 i 0 = 0) := by
  haveI : NeZero (m + 1) := ⟨Nat.succ_ne_zero m⟩
  suffices h_col : ∃ (L₁ : List (Matrix.SpecialLinearGroup (Fin (m+1)) ℤ)),
      (∀ E ∈ L₁, IsTransvec E) ∧
      (L₁.prod * τ).1 0 0 = 1 ∧
      (∀ i, i ≠ 0 → (L₁.prod * τ).1 i 0 = 0) by
    obtain ⟨L₁, hL₁, h₁_00, h₁_i0⟩ := h_col
    obtain ⟨L₂, hL₂, h₂_00, h₂_0j, h₂_i0⟩ :=
      row0_clear (L₁.prod * τ) h₁_00 h₁_i0
    exact ⟨L₁, L₂, hL₁, hL₂, h₂_00, h₂_0j, h₂_i0⟩
  by_cases hi₀_zero : i₀ = 0
  · subst hi₀_zero
    rcases h_unit with h1 | h_neg1
    · exact ⟨[], fun _ h ↦ absurd h (by simp), by simp [h1],
        fun i hi ↦ by simp [h_others i hi]⟩
    rcases m with _ | m'
    · exact absurd (show τ.1.det = -1 by simp [Matrix.det_unique, h_neg1])
        (by rw [τ.2]; norm_num)
    · exact column_pivot_of_neg_one_at_zero τ h_neg1 h_others
  · exact column_pivot_of_unit_off_diagonal τ i₀ hi₀_zero h_others h_unit

/-- Every element of `SL_m(ℤ)` is a product of transvections. -/
theorem SLnZ_transvec_gen (m : ℕ) (σ : Matrix.SpecialLinearGroup (Fin m) ℤ) :
    ∃ (L : List (Matrix.SpecialLinearGroup (Fin m) ℤ)),
      (∀ E ∈ L, IsTransvec E) ∧ σ = L.prod := by
  induction m with
  | zero =>
    refine ⟨[], fun _ h ↦ absurd h (by simp), ?_⟩
    apply Subtype.ext; ext i; exact i.elim0
  | succ m ih =>
    obtain ⟨L_col, hL_col, h_nz⟩ := col0_reduce σ
    set τ := L_col.prod * σ
    have hσ_eq : σ = L_col.prod⁻¹ * τ := by simp [τ]
    obtain ⟨L_inv, hL_inv_tv, hL_inv_eq⟩ := transvec_list_inv L_col hL_col
    obtain ⟨i₀, hi₀⟩ := col0_ne_zero τ
    have h_others := nzCount_le_one_unique_nonzero τ i₀ hi₀ h_nz
    have h_unit := sole_nonzero_col0_is_unit τ i₀ h_others
    obtain ⟨L_left, L_right, hL_left, hL_right, h00, h0j, hhi0⟩ :=
      to_block_form τ i₀ hi₀ h_others h_unit
    set τ' := L_left.prod * τ * L_right.prod
    obtain ⟨L_B, hL_B_tv, hL_B_eq⟩ := ih (extractBlock τ' h00 h0j hhi0)
    obtain ⟨L_block, hL_block_tv, hL_block_eq⟩ :=
      block_form_transvec_lift τ' h00 h0j hhi0 L_B hL_B_tv hL_B_eq
    obtain ⟨L_left_inv, hL_left_inv_tv, hL_left_inv_eq⟩ := transvec_list_inv L_left hL_left
    obtain ⟨L_right_inv, hL_right_inv_tv, hL_right_inv_eq⟩ := transvec_list_inv L_right hL_right
    refine ⟨L_inv ++ L_left_inv ++ L_block ++ L_right_inv,
      isTransvec_append _ _ (isTransvec_append _ _
        (isTransvec_append _ _ hL_inv_tv hL_left_inv_tv) hL_block_tv) hL_right_inv_tv, ?_⟩
    rw [List.prod_append, List.prod_append, List.prod_append,
        ← hL_inv_eq, ← hL_left_inv_eq, ← hL_right_inv_eq,
        ← hL_block_eq, hσ_eq]
    show L_col.prod⁻¹ * τ =
      L_col.prod⁻¹ * L_left.prod⁻¹ * (L_left.prod * τ * L_right.prod) * L_right.prod⁻¹
    group
